from __future__ import annotations

import os
from pathlib import Path


PACKAGE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = Path(os.environ.get("RELATION_GRAPH_PROJECT_ROOT") or PACKAGE_DIR.parent)
GRAPH_ASSETS_DIR = PACKAGE_DIR / "graph_assets"
RUNS_DIR = PROJECT_ROOT / "data_output" / "ui_runs"
EMBEDDED_RUNTIME_DIR = PACKAGE_DIR / "embedded_runtime"
EMBEDDED_OLLAMA_DIR = EMBEDDED_RUNTIME_DIR / "ollama"
EMBEDDED_OLLAMA_EXE = EMBEDDED_OLLAMA_DIR / "ollama.exe"
RUNTIME_STATE_DIR = PROJECT_ROOT / "runtime_state"
LOCAL_PROVIDER_CONFIG_PATH = RUNTIME_STATE_DIR / "local_provider.json"
GRAPH_VENDOR_DIR_NAME = "vendor"

DEFAULT_MODEL_ID = "doubao-seed-1-8-251228"
DEFAULT_ARK_MODEL_ID = DEFAULT_MODEL_ID
ARK_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"
ARK_ENDPOINT_PATH = "/chat/completions"
LLM_TIMEOUT_SECONDS = 120
LLM_REQUEST_RETRY_COUNT = 3
LLM_PARSE_RETRY_COUNT = 1
LOCAL_OLLAMA_HOST = "127.0.0.1"
LOCAL_OLLAMA_PORT = 11435
LOCAL_OLLAMA_BASE_URL = f"http://{LOCAL_OLLAMA_HOST}:{LOCAL_OLLAMA_PORT}"
LOCAL_OLLAMA_START_TIMEOUT_SECONDS = 20
LOCAL_PRIMARY_MODEL_ID = "qwen3.5:9b"
LOCAL_FALLBACK_MODEL_ID = "qwen3.5:4b"
LOCAL_MODEL_CANDIDATES = (LOCAL_PRIMARY_MODEL_ID, LOCAL_FALLBACK_MODEL_ID)
LOCAL_CONTEXT_LENGTH = 8192
LOCAL_TIMEOUT_SECONDS = LLM_TIMEOUT_SECONDS
LOCAL_REQUEST_RETRY_COUNT = LLM_REQUEST_RETRY_COUNT
LOCAL_PARSE_RETRY_COUNT = LLM_PARSE_RETRY_COUNT

MAX_SUCCESSFUL_RUNS = 10
MAX_PENDING_JOBS = 6
MAX_TOTAL_CHUNKS_PER_JOB = 120
ARK_MAX_CONCURRENCY = 2
ARK_MIN_REQUEST_INTERVAL_SECONDS = 1.0
MAX_FILES_PER_JOB = 10
MAX_TOTAL_UPLOAD_BYTES = 25 * 1024 * 1024
COMPLETED_JOB_TTL_SECONDS = 3600
MAX_COMPLETED_JOB_RECORDS = 50

UPLOAD_TEMP_PREFIX = "kg-ui-"
RUN_TEMP_PREFIX = ".tmp-kg-run-"
